name: build cron

on:
  schedule:
    - cron: '25 2 * * 0,4'

jobs:
  check_urls:
    if: github.repository_owner == 'vpnlo'
    uses: ./.github/workflows/check_urls.yml

  test_set_1:
    needs: check_urls
    uses: ./.github/workflows/test_set_1.yml

  test_set_2:
    needs: check_urls
    uses: ./.github/workflows/test_set_2.yml
