name: shellcheck

on: workflow_call

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'vpnlo'
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # 2.4.0
        with:
          persist-credentials: false
      - name: Check
        run: |
          if [ ! -x /usr/bin/shellcheck ]; then
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get -yqq update
            sudo apt-get -yqq install shellcheck
          fi

          cd "$GITHUB_WORKSPACE"
          pwd
          ls -ld vpnsetup.sh

          export SHELLCHECK_OPTS="-e SC1090,SC1091"
          shellcheck --version
          shopt -s globstar
          ls -ld -- **/*.sh
          shellcheck **/*.sh
